### PR TITLE
test(react): upgrade to react 17 and remove enzyme

### PR DESCRIPTION
**Pull request by ashleyryan**
- add react-testing-library
- upgrade jest/jsdom dependencies

Signed-off-by: Ashley Ryan <asryan@vmware.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [ ] If applicable, have a visual design approval

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] clarity.design website / infrastructure changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by ashleyryan** [comment]
5th time is the charm - this is going to be a lot more of a pain to bring to the main branch

**Review by coryrylan — APPROVED** [review]

**Comment by coryrylan** [comment]
I don't have any strong opinion/insight on this needing to be backported to main/v5. Might be fine just remaining on beta/v6 only?

**Comment by ashleyryan** [comment]
My only concern with not backporting it to v5 is that any fixes we make might be difficult to cherry-pick back into v5 if the react folder is so different.

But I guess we don't really do that much as far as react testing goes, so we probably won't need to make any changes there if we're fixing a core bug

**Comment by mathisscott** [comment]
> My only concern with not backporting it to v5 is that any fixes we make might be difficult to cherry-pick back into v5 if the react folder is so different.

🤔  I'm not a fan of backporting this to v5. If the need becomes dire, then maybe we can address it at that time?

**Review by mathisscott — APPROVED** [review]

**Comment by ashleyryan** [comment]
> If the need becomes dire, then maybe we can address it at that time?

Works for me. It's unlikely anyone will be editing the react unit tests anyway

**Pull request merged**
