### PR TITLE
chore: remove the Clarity Angular/UI in the issue template

### PR DESCRIPTION
**Pull request by astorije**
Since the Clarity Angular/UI and Clarity Core projects have been split into 2 repos, I believe there is no longer a need for this.

### CODE REVIEW

**Review by kevinbuhmann — APPROVED** [review]

**Comment by bbogdanov** [comment]
It is needed since we have @cds/angular

**Comment by astorije** [comment]
@bbogdanov, isn't that covered by the "Framework" section below? It seems to me that any issues opened in this repo would have "Clarity Core" checked and then "Angular" or other be selected in the "Framework" section (but I have never worked with Clarity Angular so could be wrong).

Screen Shot 2022-06-08 at 9 04 58 AM

**Comment by bbogdanov** [comment]
It is not covered cause you can use 

`@cds/core` + Angular

Or using `@cds/angular` (which underneath uses `@cds/core`)  + Angular

**Comment by ashleyryan** [comment]
I left it in here last time I cleaned up this file mostly to remind people that this was the Core repo. If they were going to report clr/angular issues I wanted it to at least be explicitly called out

**Pull request closed without merging**
